volumes:
        grafana-data:
                driver: local
        postgres-data:
                driver: local
services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
            - grafana-data:/var/lib/grafana
            - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
            - ./dashboards:/var/lib/grafana/dashboards
            - ./grafana/pg_datasource.yml:/etc/grafana/provisioning/datasources/pg_datasource.yml
            - ./grafana/custom.ini:/etc/grafana/grafana.ini
    depends_on:
            - postgres

  postgres:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
  loader:
          image: ucirp/ecu-loader
          build: 
            context: ./data_loader
            cache_from: 
              - debian:latest
          extra_hosts:
                  - "ecu:192.168.0.6"
                  - "gse_ecu:192.168.0.5"
          depends_on:
                  - postgres
                  - grafana
          volumes:
                  - ./data_loader:/root

