volumes:
        grafana-data:
                driver: local
        postgres-data:
                driver: local
services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
            - grafana-data:/var/lib/grafana

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
