volumes:
        grafana-data:
                driver: local
        postgres-data:
                driver: local
services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
            - grafana-data:/var/lib/grafana
            - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
            - ./dashboards:/var/lib/grafana/dashboards
            - ./grafana/pg_datasource.yml:/etc/grafana/provisioning/datasources/pg_datasource.yml
            - ./grafana/custom.ini:/etc/grafana/grafana.ini

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
