{
 "title": "Flight GUI",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Atmosphereic Pressure",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", pressure FROM bmp ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", temp FROM bmp ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Location",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", lat, lon FROM location ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Gyroscopic Data",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", x, y, z FROM gyro ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Acceleration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", x, y, z FROM acc ORDER BY \"time\" DESC LIMIT 1 "
    }
   ]
  }
 ]
}