{
 "title": "Virt Horizon testing",
 "time": { "from": "2023-03-11T01:31:10.102Z", "to": "2023-03-11T19:12:23.891Z" },
 "panels": [
  {
   "title": "Solenoids",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", he, lox, lng, pv1, pv2, mvas FROM soleniods ORDER BY \"time\" DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "PT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", pt1 AS \"LNG PT\", pt2 AS \"LOX PT\", pt3 AS \"COPV PT\", pt4 AS \"LNG INJ PT\" FROM pt LIMIT 50 "
    }
   ]
  },
  {
   "title": "TC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \"time\", tc1 AS \"LNG TC\", tc2 AS \"LOX TC\", tc3 AS \"COPV TC\", tc4 AS \"MVAS TC\" FROM tc LIMIT 50 "
    }
   ]
  },
  {
   "title": "COPV PT",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", pt3 FROM pt LIMIT 50 "
    }
   ]
  },
  {
   "title": "LNG PT",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", pt1 FROM pt LIMIT 50 "
    }
   ]
  },
  {
   "title": "LNG INJ PT",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", pt4 FROM pt LIMIT 50 "
    }
   ]
  },
  {
   "title": "LOX PT",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", pt2 FROM pt LIMIT 50 "
    }
   ]
  },
  {
   "title": "COPV TC",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", tc3 FROM tc LIMIT 50 "
    }
   ]
  },
  {
   "title": "LOX TC",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", tc2 FROM tc LIMIT 50 "
    }
   ]
  },
  {
   "title": "LNG TC",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", tc1 FROM tc LIMIT 50 "
    }
   ]
  },
  {
   "title": "MVAS TC",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \"time\", tc4 FROM tc LIMIT 50 "
    }
   ]
  }
 ]
}